client_max_body_size 20M;

server {
    index index.html;
    root /var/www/public/;
    resolver 127.0.0.11 valid=30s ipv6=off;
    set $backend_upstream http://{{ .Env.URL_BACKEND }};

    {{ if .Env.FRONTEND_SERVER_NAME }}
    server_name {{ .Env.FRONTEND_SERVER_NAME }};
    {{else}}
    server_name _;
    {{end}}

    include sites.d/frontend.conf;
    include include.d/letsencrypt.conf;
}

{{if .Env.BACKEND_SERVER_NAME}}
server {
    server_name {{ .Env.BACKEND_SERVER_NAME }};
    resolver 127.0.0.11 valid=30s ipv6=off;
    set $backend_upstream http://{{ .Env.URL_BACKEND }};

    include sites.d/backend.conf;
    include include.d/letsencrypt.conf;
}
{{end}}
